// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbwzLnwv3SIjJ-0aurSVInaYgafHNjMGI',
    appId: '1:687454452213:web:30b9f7ce255faf3e2908bc',
    messagingSenderId: '687454452213',
    projectId: 'sakebrewingapp',
    authDomain: 'sakebrewingapp.firebaseapp.com',
    databaseURL: 'https://sakebrewingapp-default-rtdb.firebaseio.com',
    storageBucket: 'sakebrewingapp.firebasestorage.app',
    measurementId: 'G-RRGVERTD4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAFBFJCnO5w4Xs1YKJCE04pvHMeQYn1dE',
    appId: '1:687454452213:android:2c3b9a87aa747f312908bc',
    messagingSenderId: '687454452213',
    projectId: 'sakebrewingapp',
    databaseURL: 'https://sakebrewingapp-default-rtdb.firebaseio.com',
    storageBucket: 'sakebrewingapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3RyDcS-Xo_AMGyW5JaPexZMkGB7XkbqU',
    appId: '1:687454452213:ios:7d5dfc0b4c0506612908bc',
    messagingSenderId: '687454452213',
    projectId: 'sakebrewingapp',
    databaseURL: 'https://sakebrewingapp-default-rtdb.firebaseio.com',
    storageBucket: 'sakebrewingapp.firebasestorage.app',
    iosBundleId: 'com.example.sakeBrewingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3RyDcS-Xo_AMGyW5JaPexZMkGB7XkbqU',
    appId: '1:687454452213:ios:7d5dfc0b4c0506612908bc',
    messagingSenderId: '687454452213',
    projectId: 'sakebrewingapp',
    databaseURL: 'https://sakebrewingapp-default-rtdb.firebaseio.com',
    storageBucket: 'sakebrewingapp.firebasestorage.app',
    iosBundleId: 'com.example.sakeBrewingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbwzLnwv3SIjJ-0aurSVInaYgafHNjMGI',
    appId: '1:687454452213:web:58bb23a125cfd3252908bc',
    messagingSenderId: '687454452213',
    projectId: 'sakebrewingapp',
    authDomain: 'sakebrewingapp.firebaseapp.com',
    databaseURL: 'https://sakebrewingapp-default-rtdb.firebaseio.com',
    storageBucket: 'sakebrewingapp.firebasestorage.app',
    measurementId: 'G-13PN1GMG29',
  );
}
